# https://taskfile.dev

version: '3'

vars:
  EXPORT_TOOL_VERSION: 2.0.0
  DOCKER_IMAGE: 'quay.io/wire/backup-export-tool:{{ .EXPORT_TOOL_VERSION }}'

tasks:
  default:
    cmds:
      - task: build

  git-submodules:
    status:
      - test -f "{{ joinPath .TASKFILE_DIR "helium" ".gitignore" }}"
      - test -f "{{ joinPath .TASKFILE_DIR "xenon" ".gitignore" }}"
    cmds:
      - git submodule update --init --recursive

  build:
    deps: [git-submodules]
    vars:
      GRADLEW_FILENAME: '{{ if eq OS "windows" }}gradlew.bat{{ else }}gradlew{{ end }}'
      RUN: '{{ if eq OS "windows" }}cmd /D /E:ON /C{{ else }}bash -c{{ end }}'
    cmds:
      - cmd: |
          {{.RUN}} call "{{ joinPath .TASKFILE_DIR .GRADLEW_FILENAME }}" build

  docker-get:
    cmds:
      - docker pull {{ .DOCKER_IMAGE }}
      - docker run --rm -it -v "{{ joinPath .TASKFILE_DIR "app" }}":/app_copy {{ .DOCKER_IMAGE }} bash -c "cp -r /app/* /app_copy"

  docker-run:
    interactive: true
    cmds:
      - docker run -it -v "{{ joinPath .TASKFILE_DIR "app" }}":"/app_copy" --entrypoint /bin/sh {{ .DOCKER_IMAGE }}

  docker-debug:
    interactive: true
    cmds:
      - docker exec -it -v "{{ joinPath .TASKFILE_DIR "app" }}":"/app_copy" {{ .DOCKER_IMAGE }} /bin/sh
