# https://taskfile.dev

version: '3'

vars:
  EXPORT_TOOL_VERSION: 2.0.0
  DOCKER_IMAGE: 'quay.io/joelvaneenwyk/wire-app-backup-tool:{{ .EXPORT_TOOL_VERSION }}'

tasks:
  default:
    cmds:
      - task: build

  git-submodules:
    status:
      - test -f "{{ joinPath .TASKFILE_DIR "lib" "helium" ".gitignore" }}"
      - test -f "{{ joinPath .TASKFILE_DIR "lib" "xenon" ".gitignore" }}"
    cmds:
      - git add .
      - git submodule update --init --recursive

  build:
    deps: [git-submodules]
    vars:
      GRADLEW_FILENAME: '{{ if eq OS "windows" }}gradlew.bat{{ else }}gradlew{{ end }}'
      RUN: '{{ if eq OS "windows" }}cmd /D /E:ON /C{{ else }}bash -c{{ end }}'
    cmds:
      - cmd: |
          {{.RUN}} call "{{ joinPath .TASKFILE_DIR .GRADLEW_FILENAME }}" build

  create-shadow-jar:
    deps: [build]
    cmds:
      - cmd: ./gradlew shadowJar

  docker-build:
    cmds:
      - cmd: docker build -t joelvaneenwyk/wire-app-backup-tool .

  docker-push:
    cmds:
      - cmd: docker push joelvaneenwyk/wire-app-backup-tool

  extract:
    cmds:
      - cmd: >-
          docker run
          --rm -it
          -v "{{ joinPath .TASKFILE_DIR "assets" "wire_sample_backup.desktop_wbu" }}":/app/database-in
          -v "{{ joinPath .TASKFILE_DIR "assets" "output" }}":/app/database-out
          -e CLIENT_TYPE="${CLIENT_TYPE}"
          -e WIRE_USER="${WIRE_USER}"
          -e WIRE_PASSWORD="${WIRE_PASSWORD}"
          -e BACKUP_PASSWORD="${BACKUP_PASSWORD}"
          -e BACKUP_USERNAME="${BACKUP_USER}"
          -e WIRE_API_HOST="${WIRE_API_HOST}"
          -e USE_PROXY="${USE_PROXY}"
          -e PROXY_URL="${PROXY_URL}"
          -e PROXY_PORT="${PROXY_PORT}"
          -e NON_PROXY_HOSTS="${NON_PROXY_HOSTS}"
          {{ .DOCKER_IMAGE }}
    vars:
      DOCKER_IMAGE: '{{ .DOCKER_IMAGE | default "quay.io/wire/backup-export-tool:latest" }}'

      CLIENT_TYPE: '{{ .CLIENT_TYPE | default "web" }}'
      WIRE_USER: '{{ .WIRE_USER | default "my.wire.user@gmail.com" }}'
      WIRE_PASSWORD: '{{ .WIRE_PASSWORD | default "" }}'

      BACKUP_USER:
      BACKUP_PASSWORD:

      WIRE_API_HOST: '{{ .WIRE_API_HOST | default "https://prod-nginz-https.wire.com" }}'

      USE_PROXY:
      PROXY_URL:
      PROXY_PORT:
      NON_PROXY_HOSTS:

  docker-get:
    cmds:
      - docker pull {{ .DOCKER_IMAGE }}
      - docker run --rm -it -v "{{ joinPath .TASKFILE_DIR "app" }}":/app_copy {{ .DOCKER_IMAGE }} bash -c "cp -r /app/* /app_copy"

  docker-run:
    interactive: true
    cmds:
      - docker run -it -v "{{ joinPath .TASKFILE_DIR "app" }}":"/app_copy" --entrypoint /bin/sh {{ .DOCKER_IMAGE }}

  docker-debug:
    interactive: true
    cmds:
      - docker exec -it -v "{{ joinPath .TASKFILE_DIR "app" }}":"/app_copy" {{ .DOCKER_IMAGE }} /bin/sh
