/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Support convention plugins written in Kotlin. Convention plugins are build scripts in 'src/main' that automatically become available as plugins in the main build.
    `kotlin-dsl`
}

repositories {
    // Use the plugin portal to apply community plugins in convention plugins.
    gradlePluginPortal()
    mavenCentral()
    google()
    mavenLocal()
}

dependencies {
    implementation(libs.github.johnrengelman.shadow)
    implementation(libs.kotlin.gradle.plugin)

    implementation(libs.wire.xenon)
    implementation(libs.wire.helium)

    api(libs.fasterxml.jackson.jaxrs.jackson.jaxrs.json.provider)
    api(libs.jakarta.ws.rs.jakarta.ws.rs.api)
    api(libs.flywaydb.flyway.core)
    api(libs.glassfish.jersey.core.jersey.client)
    api(libs.glassfish.jersey.inject.jersey.hk2)
    api(libs.glassfish.tyrus.bundles.tyrus.standalone.client)

    testImplementation(libs.slf4j.api)
    testImplementation(libs.slf4j.log4j12)
    testImplementation(libs.javax.activation.activation)
    testImplementation(libs.postgresql.postgresql)
    testImplementation(libs.junit.jupiter)
    testImplementation(libs.junit.jupiter.engine)
}
