name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build_server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set envs
        # set release version to the latest commit
        run: echo "RELEASE_VERSION=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Build docker image, push if the branch is master
        uses: docker/build-push-action@v1
        with:
          # login to repo
          repository: lukaswire/backup-export-tool
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          # pass release_version
          build_args: release_version=${{ env.RELEASE_VERSION }}
          # tag the image with latest git tag
          tag_with_ref: true
          # add labels from the git
          add_git_labels: true
          # push only if this is build in the master branch
          push: ${{ startsWith(github.ref, 'refs/heads/master') }}
