name: CI test pipelines

on:
  push:
    branches: [main, develop, master]
  pull_request:
    branches: [main, develop, master]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: Java ${{ matrix.java }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-20.04 ]
        java: [ 11 ]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          # Running setup-java again overwrites the settings.xml
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Display JDK version
        run: |
          java -version

      - name: Build application
        run: |
          ./gradlew assemble

      - name: Build final shadow jar
        run: |
          ./gradlew shadowJar

      - name: Run tests application
        run: |
          ./gradlew test --info
