name: CI test pipelines

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: Java ${{ matrix.java }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        java: [ 8, 11 ]

    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Display JDK version
        run: |
          java -version

      - name: Build application
        run: |
          ./gradlew assemble

      - name: Build final shadow jar
        run: |
          ./gradlew shadowJar

      - name: Run tests application
        run: |
          ./gradlew test --info
