name: Release Pipeline

on:
  release:
    types: [ published ]

jobs:
  docker_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set envs
        # use latest tag as release version
        run: echo "RELEASE_VERSION=${GITHUB_REF:10}" >> $GITHUB_ENV

      - name: Build and publish docker image
        uses: docker/build-push-action@v1
        with:
          # login to repo
          repository: quay.io/wire/backup-export-tool
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          # pass release_version
          build_args: release_version=${{ env.RELEASE_VERSION }}
          # tag the image with latest git tag
          tag_with_ref: true
          # add labels from the git
          add_git_labels: true
          # push only if this is the build containing tags
          push: ${{ startsWith(github.ref, 'refs/tags/') }}

      # Send webhook to Wire using Slack Bot
      - name: Webhook to Wire
        uses: 8398a7/action-slack@v2
        with:
          status: ${{ job.status }}
          author_name: Backups Exports Docker Release Pipeline
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.WEBHOOK_RELEASE }}
        # Notify every release
        if: always()

  jar_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # sets up jdk
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 8

      # Builds application
      - name: Build application
        run: |
          ./gradlew shadowJar

      # Creates release zip
      - name: Create release zip
        run: |
          cp build/libs/backup-export.jar .
          zip -r backup-export.zip backup-export.jar libs README.md

      # Obtains release URL to upload assets
      - name: Get Release Id
        id: get_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: bruceadams/get-release@v1.2.0

      # Upload ganymede zip to the releases
      - name: Upload Ganymede Release
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: backup-export.zip
          asset_name: backup-export.zip
          asset_content_type: application/zip

      # Send webhook to Wire using Slack Bot
      - name: Webhook to Wire
        uses: 8398a7/action-slack@v2
        with:
          status: ${{ job.status }}
          author_name: Backups Exports JAR Release Pipeline
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.WEBHOOK_RELEASE }}
        # Notify every release
        if: always()
